version: "3.8"
        
services:
    php:
        build:
            context: ./
            target: base
            dockerfile: dockerfile
        environment:             
            - "TZ=Turkey"
        volumes: 
            - "./frontend:/var/www/html"
            - "./backend:/var/www/html/backend"
            ##- "./backend/vendor:/var/www/html/backend/vendor"
            - "./developer.sh:/developer.sh"
        command: 
            - "/developer.sh"
        ports:
            - "8002:80"
    mysql:
        image: mysql:8.0.28
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        command: 
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_turkish_ci"
        environment:
            TZ: Turkey
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: dojo
        ports:
            - 3307:3306
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
            - my8vol:/data/db

volumes:
    my8vol:
